name: Tests

on:
  push:
    branches: [ main, chore/**, feat/**, fix/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest pytest-cov

      - name: Run tests
        env:
          TZ: America/Sao_Paulo
        run: |
          mkdir -p test_results
          pytest \
            --cov-config=.coveragerc \
            --cov=src --cov=sources \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage.xml \
            --cov-report=html \
            --junitxml=test_results/junit.xml \
            -o junit_family=legacy

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test_results/junit.xml
            coverage.xml
            htmlcov/

      - name: Upload test results to Codecov (unit)
        if: always()
        uses: codecov/test-results-action@v1
        with:
          files: test_results/junit.xml
          flags: unit
          use_oidc: true
          disable_search: true
          fail_ci_if_error: false
          verbose: true

      - name: Verify coverage file (unit)
        if: always()
        run: |
          echo "Verificando coverage.xml"
          ls -l coverage.xml || true
          wc -c coverage.xml || true
          head -n 5 coverage.xml || true

      - name: Upload coverage to Codecov (unit) [try 1]
        id: codecov_unit_try1
        if: always()
        continue-on-error: true
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unit
          disable_search: true
          fail_ci_if_error: true
          verbose: true
          use_oidc: true

      - name: Upload coverage to Codecov (unit) [retry if failed]
        if: ${{ always() && steps.codecov_unit_try1.outcome == 'failure' }}
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unit
          disable_search: true
          fail_ci_if_error: false
          verbose: true
          use_oidc: true

      - name: Upload test results to Codecov (Tests Analytics)
        if: always()
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: test_results/junit.xml
          flags: unit

  e2e_happy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest pytest-cov

      - name: Run all E2E with coverage (no gate)
        env:
          TZ: America/Sao_Paulo
        run: |
          mkdir -p test_results_e2e
          pytest -q -c /dev/null \
            tests/integration/test_phase2_e2e_*.py \
            --cov-config=.coveragerc \
            --cov=src \
            --cov=sources \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage_e2e.xml \
            --cov-report=html:htmlcov-e2e \
            --junitxml=test_results_e2e/junit.xml \
            -o junit_family=legacy

      - name: Upload E2E artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-happy-artifacts
          path: |
            test_results_e2e/junit.xml
            coverage_e2e.xml
            htmlcov-e2e/

      - name: Upload test results to Codecov (e2e)
        if: always()
        uses: codecov/test-results-action@v1
        with:
          files: test_results_e2e/junit.xml
          flags: e2e
          use_oidc: true
          disable_search: true
          fail_ci_if_error: false
          verbose: true
      
      - name: Verify coverage file (e2e)
        if: always()
        run: |
          echo "Verificando coverage_e2e.xml"
          ls -l coverage_e2e.xml || true
          wc -c coverage_e2e.xml || true
          head -n 5 coverage_e2e.xml || true

      - name: Upload coverage to Codecov (e2e) [try 1]
        id: codecov_e2e_try1
        if: always()
        continue-on-error: true
        uses: codecov/codecov-action@v4
        with:
          files: coverage_e2e.xml
          flags: e2e
          disable_search: true
          fail_ci_if_error: true
          verbose: true
          use_oidc: true

      - name: Upload coverage to Codecov (e2e) [retry if failed]
        if: ${{ always() && steps.codecov_e2e_try1.outcome == 'failure' }}
        uses: codecov/codecov-action@v4
        with:
          files: coverage_e2e.xml
          flags: e2e
          disable_search: true
          fail_ci_if_error: false
          verbose: true
          use_oidc: true
      
      - name: Upload E2E test results to Codecov (Tests Analytics)
        if: always()
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: test_results_e2e/junit.xml
          flags: e2e
  
  integration:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest pytest-cov

      - name: Run integration tests with coverage (no gate)
        env:
          TZ: America/Sao_Paulo
        run: |
          mkdir -p test_results_integration
          pytest -q -c /dev/null -m integration \
            --cov-config=.coveragerc \
            --cov=src \
            --cov=sources \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage_integration.xml \
            --cov-report=html:htmlcov-integration \
            --junitxml=test_results_integration/junit.xml \
            -o junit_family=legacy

      - name: Upload integration artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-artifacts
          path: |
            test_results_integration/junit.xml
            coverage_integration.xml
            htmlcov-integration/

      - name: Upload test results to Codecov (integration)
        if: always()
        uses: codecov/test-results-action@v1
        with:
          files: test_results_integration/junit.xml
          flags: integration
          use_oidc: true
          disable_search: true
          fail_ci_if_error: false
          verbose: true

      - name: Verify coverage file (integration)
        if: always()
        run: |
          echo "Verificando coverage_integration.xml"
          ls -l coverage_integration.xml || true
          wc -c coverage_integration.xml || true
          head -n 5 coverage_integration.xml || true

      - name: Upload coverage to Codecov (integration) [try 1]
        id: codecov_integration_try1
        if: always()
        continue-on-error: true
        uses: codecov/codecov-action@v4
        with:
          files: coverage_integration.xml
          flags: integration
          disable_search: true
          fail_ci_if_error: true
          verbose: true
          use_oidc: true

      - name: Upload coverage to Codecov (integration) [retry if failed]
        if: ${{ always() && steps.codecov_integration_try1.outcome == 'failure' }}
        uses: codecov/codecov-action@v4
        with:
          files: coverage_integration.xml
          flags: integration
          disable_search: true
          fail_ci_if_error: false
          verbose: true
          use_oidc: true

      - name: Upload integration test results to Codecov (Tests Analytics)
        if: always()
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: test_results_integration/junit.xml
          flags: integration
